import "MainWindowViewModel.idl";

namespace ShapeViewer
{
[default_interface] runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        MainWindowViewModel ViewModel
        {
            get;
        };
    }
}
